name: Build WarRegions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Verify namespace consistency
      run: |
        echo "=== التحقق من Namespaces ==="
        find . -name "*.cs" -exec grep -l "namespace WarRegions" {} \; | wc -l
        echo "ملف باستخدام namespace موحد"
        
    - name: Build solution
      run: dotnet build WarRegions.sln --configuration Release --verbosity minimal
      
    - name: Upload successful build
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: warregions-game
        path: |
          CLI/bin/Release/net8.0/
          Core/bin/Release/net8.0/
